import "./globals.css";
import type { Metadata } from "next";
import { inter, ubuntun } from "./font";
import { Sidebar } from "./components/navigation/navsidebar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${ubuntun.variable}`}
        suppressHydrationWarning={true}
      >
        <div className="flex bg-white h-screen w-full">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
